require("plugs.nvim-tree")
require("plugs.nvim-cmp")
require("plugs.nvim-lspconfig")
require("plugs.snippets")
require("plugs.nvim-treesitter")
require("plugs.formatter")
require("plugs.ui")
require("plugs.edit")
