require('plugs.nvim-tree')
require('plugs.nvim-cmp')
require('plugs.nvim-lspconfig')
require('plugs.nvim-treesitter')
require('telescope')
require('plugs.emmet-vim')
require('plugs.ui')
require('plugs.term')
